### ISSUE TITLE
Support templating for rollovers

### ISSUE THREAD

**Issue by Jephuff** [oncojs/oncogrid#7]
Accept template for rollovers, allowing more flexible use with fields/wording

Example: 
`'Donor: ' + _self.donors[xIndex].id + '</br>'`
could be represented as
`'Donor: {{id}}</br>'`

**Comment by andricDu** [comment]
Is this something that you are currently working on?

**Comment by Jephuff** [comment]
@andricDu no, this was address by a previous pull request. I must have forgotten to add the issue number.
